export const Landing = '/'
export const SignUp = '/signup'
export const SignIn = '/signin'
export const Account = '/account'
export const Admin = '/admin'
export const Doctor = '/doctor'
export const Patient = '/patient'
export const PasswordForget = '/pw-forget'
